### ISSUE TITLE
display one instance of the patient per golden record in the MPI

### ISSUE THREAD

**Issue by TW-cwhite** [IsantePlus/openmrs-module-registrationapp#36]
display one result for records that are matched in the MPI

**Comment by pmanko** [comment]
We should get a patient's linked records using the `&_include=Patient:link` parameter, and pull the Patient record that was created first or tagged in some way as original. 

Then, we can display that patient's data as a single entry. Basically, we should not have multiple entries as possible registration matches for a single golden record in the MPI
